### PR TITLE
Updated config.go - Externalizing svg data to meshmodel_metadata.json

### PR DESCRIPTION
**Pull request by b0id**
**Description**

This PR fixes ([Adapters] Config.go: lint error due to long SVG line) #101

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by b0id** [comment]
@Revolyssup @leecalcote  fyi

**Comment by Revolyssup** [comment]
@b0id Would you lowercase and hyphenate the keys? Refer to column names here https://docs.google.com/spreadsheets/u/2/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=0

**Review by Revolyssup — CHANGES_REQUESTED** [review]
@b0id Would you lowercase and hyphenate the keys? Refer to column names here https://docs.google.com/spreadsheets/u/2/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=0

**Comment by b0id** [comment]
Yes, I thought you might say that.  Will do.

**Comment by b0id** [comment]
@Revolyssup done.

**Comment by leecalcote** [comment]
🚀

**Pull request merged**
